{% set name = "napari-roi" %}
{% set version = "0.1.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/napari-roi-{{ version }}.tar.gz
  sha256: cadaad0c6c6b94df16165c8f3ec224ebf25b6b51fcae994ccaacb275e2d6a72e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools-scm
  run:
    - napari >=0.4.12
    - napari-plugin-engine >=0.1.4
    - numpy
    - pandas
    - python >=3.7
    - qtpy
    - vispy

test:
  imports:
    - napari_roi
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/BodenmillerGroup/napari-roi
  summary: Select regions of interest (ROIs) using napari
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - conda-forge/napari
    - jwindhager
